In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ejercicio 1

## ejercicio 1

In [21]:
df = pd.read_csv('ventas_historicas.csv')

In [22]:
df.shape

(300, 10)

In [23]:
df.dtypes

id_venta         int64
mes             object
region          object
vendedor        object
categoria       object
canal           object
cantidad         int64
precio_unit    float64
descuento      float64
monto_bruto    float64
dtype: object

In [24]:
df.head(5)

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,1001,Junio,Norte,Laura Diaz,Laptop,Online,4,769.94,0.0,3079.76
1,1002,Enero,Oeste,Carlos Rivas,Laptop,Online,4,894.32,0.0,3577.28
2,1003,Abril,Oeste,Laura Diaz,Tablet,Online,13,375.14,15.0,4876.82
3,1004,Enero,Este,Camila Vega,Laptop,Online,6,1010.65,NaN,6063.90
4,1005,Enero,Norte,Laura Diaz,Teclado,NaN,10,78.27,0.0,782.70

In [25]:
df.isnull()

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
295,False,False,False,False,False,False,False,False,False,False
296,False,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False

In [26]:
df.isnull().sum()

id_venta        0
mes             0
region          0
vendedor       21
categoria       0
canal          11
cantidad        0
precio_unit     0
descuento      11
monto_bruto     0
dtype: int64

## ejercicio 2

In [27]:
hola = df[(df['region'] == "centro") & (df["monto_bruto"]> 300)] 
print(f"Días con monto : {len(hola)}")

Días con monto : 0

## ejercicio 3

In [28]:
hola2 = df[(df['canal'] == "Online") & (df["monto_bruto"]>= 15)] 
hola2[[ "region", "categoria", "cantidad", "monto_bruto", "descuento"]]

     region    categoria  cantidad  monto_bruto  descuento
0     Norte       Laptop         4      3079.76        0.0
1     Oeste       Laptop         4      3577.28        0.0
2     Oeste       Tablet        13      4876.82       15.0
3      Este       Laptop         6      6063.90        NaN
5       Sur      Monitor         7      1951.18       15.0
..      ...          ...       ...          ...        ...
291     Sur  Auriculares         9      1161.36       10.0
292     Sur      Teclado         2       157.12        0.0
295     Sur      Teclado         8       574.72        0.0
297  Centro       Laptop         1      1036.18       20.0
298   Oeste      Teclado        11       761.20       10.0

[98 rows x 5 columns]

## ejercicio 4

In [29]:
df_filtrado = df[df['categoria'].isin(['Laptop', 'Tablet'])]
print(f"son {len(df_filtrado)} filas")

son 97 filas

## ejercicio 5

In [30]:
filtro_unidades = df[df['cantidad'].between(8, 15)]
print(filtro_unidades.sort_values(by='monto_bruto', ascending=False).head(10))

     id_venta      mes  region         vendedor categoria          canal  \
25       1026     Mayo   Norte              NaN    Laptop      Mayorista
207      1208    Abril     Sur  Roberto Fuentes    Laptop            NaN
88       1089    Junio   Oeste      Maria Lopez    Laptop  Tienda fisica
47       1048  Febrero   Norte  Roberto Fuentes    Laptop      Mayorista
11       1012    Junio  Centro     Carlos Rivas    Laptop      Mayorista
223      1224    Junio   Norte      Camila Vega    Laptop      Mayorista
94       1095    Junio   Oeste              NaN    Laptop  Tienda fisica
165      1166  Febrero     Sur       Ana Torres    Laptop  Tienda fisica
171      1172  Febrero   Oeste     Carlos Rivas    Laptop         Online
245      1246  Febrero    Este      Maria Lopez    Laptop      Mayorista

     cantidad  precio_unit  descuento  monto_bruto
25         15      1012.42        0.0     15186.30
207        15       977.16       20.0     14657.40
88         15       966.15       10.0     14492.25
47         14       983.79        5.0     13773.06
11         15       905.07        0.0     13576.05
223        13      1040.82        0.0     13530.66
94         14       945.13        0.0     13231.82
165        15       827.93        5.0     12418.95
171        13       941.86        0.0     12244.18
245        14       857.92        0.0     12010.88

### ¿Por qué en Pandas se usan & y | en lugar de and y or para combinar condiciones?

#### para evaluar cada fila individualmente y poder usar muchos conjuntos de datos filtrados de forma mas rapida

### ¿Que ventaja tiene .isin() frente a escribir multiples condiciones con |?

#### por que es mas legible, facil de mantener y mejora el rendimiento para listas mas grandes

# ejercicio 2

## ejercicio 1

In [31]:
resultado = df[(df['mes'].isin(['Enero', 'Febrero'])) & (df['categoria'].isin(['Laptop', 'Tablet'])) & (df['descuento'] > 10)
]

print(f"ventas: {len(resultado)}")
print(resultado.head())

ventas: 6
     id_venta      mes  region         vendedor categoria          canal  \
15       1016  Febrero  Centro  Roberto Fuentes    Tablet      Mayorista
23       1024  Febrero   Oeste      Camila Vega    Laptop         Online
149      1150  Febrero   Oeste      Maria Lopez    Tablet         Online
157      1158  Febrero    Este       Ana Torres    Tablet  Tienda fisica
187      1188  Febrero   Oeste     Javier Munoz    Tablet      Mayorista

     cantidad  precio_unit  descuento  monto_bruto
15          3       305.93       20.0       917.79
23          7       812.67       20.0      5688.69
149         2       309.86       20.0       619.72
157        15       378.21       15.0      5673.15
187        12       312.03       20.0      3744.36

## ejercicio 2

In [32]:
top_5 = resultado.sort_values(by='monto_bruto', ascending=False).head(5)
print(top_5)

     id_venta      mes  region         vendedor categoria          canal  \
23       1024  Febrero   Oeste      Camila Vega    Laptop         Online
157      1158  Febrero    Este       Ana Torres    Tablet  Tienda fisica
187      1188  Febrero   Oeste     Javier Munoz    Tablet      Mayorista
297      1298    Enero  Centro       Laura Diaz    Laptop         Online
15       1016  Febrero  Centro  Roberto Fuentes    Tablet      Mayorista

     cantidad  precio_unit  descuento  monto_bruto
23          7       812.67       20.0      5688.69
157        15       378.21       15.0      5673.15
187        12       312.03       20.0      3744.36
297         1      1036.18       20.0      1036.18
15          3       305.93       20.0       917.79

## ejercicio 3

In [33]:
promedio_general = df['monto_bruto'].mean()

filtro_especial = df[(df['region'].isin(['Norte', 'Sur'])) & (df['cantidad'] >= 10) & (df['monto_bruto'] > promedio_general)
]
print(f"promedio general: {promedio_general:.2f}")
print(f"registros: {len(filtro_especial)}")
print(filtro_especial.head())

promedio general: 2431.09
registros: 22
    id_venta      mes region      vendedor categoria          canal  cantidad  \
25      1026     Mayo  Norte           NaN    Laptop      Mayorista        15
36      1037    Abril    Sur    Ana Torres    Tablet         Online        12
37      1038  Febrero    Sur  Carlos Rivas   Monitor  Tienda fisica        14
42      1043    Abril    Sur  Carlos Rivas   Monitor      Mayorista        15
46      1047     Mayo  Norte  Javier Munoz   Monitor         Online        14

    precio_unit  descuento  monto_bruto
25      1012.42        0.0     15186.30
36       390.33       20.0      4683.96
37       250.99        5.0      3513.86
42       284.80        0.0      4272.00
46       356.93        0.0      4997.02

## ejercicio 4

In [34]:
filto_Bakan = filtro_especial['region'].value_counts()

filto_no_Bakan = df[(df['region'].isin(['Norte', 'Sur'])) & (df['monto_bruto'] > promedio_general)]['region'].value_counts()

print("Ventas con el filtro de cantidad (>= 10):")
print(filto_Bakan)
print("\nVentas sin filtro de cantidad (todas las cantidades):")
print(filto_no_Bakan)

Ventas con el filtro de cantidad (>= 10):
Norte    13
Sur       9
Name: region, dtype: int64

Ventas sin filtro de cantidad (todas las cantidades):
Norte    17
Sur      13
Name: region, dtype: int64

## ejercicio 5

In [35]:
def filtrar_ventas(df, region, categoria, monto_minimo):

    filtro = (df['region'] == region) & \
             (df['categoria'] == categoria) & \
             (df['monto_bruto'] >= monto_minimo)
    
    return df[filtro]

prueba1 = filtrar_ventas(df, 'Norte', 'Laptop', 1000)
prueba2 = filtrar_ventas(df, 'Sur', 'Tablet', 150)
prueba3 = filtrar_ventas(df, 'Centro', 'Accesorios', 50)

print(f"Resultado 1: {len(prueba1)} ")
print(f"Resultado 2: {len(prueba2)} ")
print(f"Resultado 3: {len(prueba3)} ")

Resultado 1: 10
Resultado 2: 6
Resultado 3: 0

# ejercicio 3

## ejercicio 1

## ejercicio 2

## ejercicio 3

## ejercicio 4

## ejercicio 5

# ejercicio 4

## ejercicio 1

## ejercicio 2

## ejercicio 3

## ejercicio 4

## ejercicio 5